This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./TFG-TFM_EPS_UA.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file TFG-TFM_EPS_UA.acn....done (182 entries accepted, 0 rejected).
Sorting entries.....done (1672 comparisons).
Generating output file TFG-TFM_EPS_UA.acr....done (60 lines written, 0 warnings).
Output written in TFG-TFM_EPS_UA.acr.
Transcript written in TFG-TFM_EPS_UA.alg.
